version: "3.4"

services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-ROOTUSER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-CHANGEME123}
    volumes:
      - minio:/data
    command: server /data --console-address ":9090"

volumes:
  minio: